services:
  prod.admin-sample-api:
    image: admin-sample-api:latest
    restart: no
    environment:
      APP_NAME: admin-sample-api
      SPRING_PROFILE: prod
    networks:
      - prod-default

  local.admin-sample-api:
    image: admin-sample-api:latest
    restart: no
    environment:
      APP_NAME: admin-sample-api
      SPRING_PROFILE: local
    networks:
      - local-default

networks:
  prod-default:
    external: true
  local-default:
    external: true