services:
  local.zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: local.zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - 2181:2181
    networks:
      - local-default

  local.kafka:
    image: confluentinc/cp-kafka:latest
    container_name: local.kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: local.zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://local.kafka:9092,PLAINTEXT_HOST://local.kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - local-default
    depends_on:
      - local.zookeeper

networks:
  prod-default:
    external: true
  local-default:
    external: true