services:
  prod.mariadb-develop:
    image: mariadb:latest
    container_name: prod.mariadb-develop
    ports:
      - 13306:3306
    restart: no
    volumes:
      - mariadb-develop_data:/var/lib/mysql
    env_file: mariadb/develop.env
    environment:
      TZ: Asia/Seoul
    networks:
      - prod-default

  local.mariadb-develop:
    image: mariadb:latest
    container_name: local.mariadb-develop
    ports:
      - 3306:3306
    restart: no
    volumes:
      - mariadb-develop_data:/var/lib/mysql
    env_file: mariadb/develop.env
    environment:
      TZ: Asia/Seoul
    networks:
      - local-default

volumes:
  mariadb-develop_data:

networks:
  prod-default:
    external: true
  local-default:
    external: true