services:
  prod.mariadb-market-product:
    image: mariadb:latest
    container_name: prod.mariadb-market-product
    ports:
      - 13405:3405
    restart: always
    volumes:
      - mariadb-market-product_data:/var/lib/mysql
    env_file: mariadb/market-product.env
    environment:
      TZ: Asia/Seoul
    command:
      - --log-bin
      - --log-basename=log_mariadb
      - --binlog_format=ROW
    networks:
      - prod-default

  local.mariadb-market-product:
    image: mariadb:latest
    container_name: local.mariadb-market-product
    ports:
      - 3405:3405
    restart: always
    volumes:
      - mariadb-market-product_data:/var/lib/mysql
    env_file: mariadb/market-product.env
    environment:
      TZ: Asia/Seoul
    command:
      - --log-bin
      - --log-basename=log_mariadb
      - --binlog_format=ROW
    networks:
      - local-default

volumes:
  mariadb-market-product_data:

networks:
  prod-default:
    external: true
  local-default:
    external: true