services:
  prod.mariadb-market-delivery:
    image: mariadb:latest
    container_name: prod.mariadb-market-delivery
    ports:
      - 13402:3402
    restart: no
    volumes:
      - mariadb-market-delivery_data:/var/lib/mysql
    env_file: mariadb/market-delivery.env
    environment:
      TZ: Asia/Seoul
    command:
      - --log-bin
      - --log-basename=log_mariadb
      - --binlog_format=ROW
    networks:
      - prod-default

  local.mariadb-market-delivery:
    image: mariadb:latest
    container_name: local.mariadb-market-delivery
    ports:
      - 3402:3402
    restart: no
    volumes:
      - mariadb-market-delivery_data:/var/lib/mysql
    env_file: mariadb/market-delivery.env
    environment:
      TZ: Asia/Seoul
    command:
      - --log-bin
      - --log-basename=log_mariadb
      - --binlog_format=ROW
    networks:
      - local-default

volumes:
  mariadb-market-delivery_data:

networks:
  prod-default:
    external: true
  local-default:
    external: true