services:
  prod.mariadb-market-inventory:
    image: mariadb:latest
    container_name: prod.mariadb-market-inventory
    ports:
      - 13403:3403
    restart: no
    volumes:
      - mariadb-market-inventory_data:/var/lib/mysql
    env_file: mariadb/market-inventory.env
    environment:
      TZ: Asia/Seoul
    command:
      - --log-bin
      - --log-basename=log_mariadb
      - --binlog_format=ROW
    networks:
      - prod-default

  local.mariadb-market-inventory:
    image: mariadb:latest
    container_name: local.mariadb-market-inventory
    ports:
      - 3403:3403
    restart: no
    volumes:
      - mariadb-market-inventory_data:/var/lib/mysql
    env_file: mariadb/market-inventory.env
    environment:
      TZ: Asia/Seoul
    command:
      - --log-bin
      - --log-basename=log_mariadb
      - --binlog_format=ROW
    networks:
      - local-default

volumes:
  mariadb-market-inventory_data:

networks:
  prod-default:
    external: true
  local-default:
    external: true