services:
  prod.market-delivery-api:
    image: market-delivery-api:latest
    restart: no
    environment:
      APP_NAME: market-delivery-api
      SPRING_PROFILE: prod
    volumes:
      - market_upload:/upload
    networks:
      - prod-default

  local.market-delivery-api:
    image: market-delivery-api:latest
    restart: no
    environment:
      APP_NAME: market-delivery-api
      SPRING_PROFILE: local
    volumes:
      - market_upload:/upload
    networks:
      - local-default

volumes:
  market_upload:

networks:
  prod-default:
    external: true
  local-default:
    external: true