services:
  prod.market-product-api:
    image: market-product-api:latest
    restart: always
    environment:
      APP_NAME: market-product-api
      SPRING_PROFILE: prod
    networks:
      - prod-default

  local.market-product-api:
    image: market-product-api:latest
    restart: always
    environment:
      APP_NAME: market-product-api
      SPRING_PROFILE: local
    networks:
      - local-default

networks:
  prod-default:
    external: true
  local-default:
    external: true