services:
  prod.market-inventory-api:
    image: market-inventory-api:latest
    restart: always
    environment:
      APP_NAME: market-inventory-api
      SPRING_PROFILE: prod
    networks:
      - prod-default

  local.market-inventory-api:
    image: market-inventory-api:latest
    restart: always
    environment:
      APP_NAME: market-inventory-api
      SPRING_PROFILE: local
    networks:
      - local-default

networks:
  prod-default:
    external: true
  local-default:
    external: true