services:
  prod.web-admin:
    image: web-admin:latest
    restart: no
    networks:
      - prod-default

  local.web-admin:
    image: web-admin:latest
    restart: no
    networks:
      - local-default

networks:
  prod-default:
    external: true
  local-default:
    external: true